package com.limelight.console.transition;

public enum LaunchTransitionState {
    IDLE,
    PREPARING_SESSION,
    CONNECTING_STREAM,
    WAITING_FOR_VIDEO_SURFACE,
    PLAYNITE_STARTING,
    PLAYNITE_PROCESS_RUNNING,
    PLAYNITE_FULLSCREEN_STARTING,
    PLAYNITE_FULLSCREEN_READY,
    GAME_START_REQUESTED,
    GAME_STARTING,
    GAME_PROCESS_RUNNING,
    GAME_WINDOW_STABILIZING,
    GAME_READY,
    GAME_RUNNING,
    GAME_STOPPING,
    PLAYNITE_RETURNING,
    PLAYNITE_STOPPING,
    CLOSING_STREAM,
    RETURNING_TO_DASHBOARD,
    CANCELLED,
    TIMED_OUT,
    ERROR
}
